name: dadanmaxo

on:
  workflow_dispatch:
  schedule:
    - cron: '2 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: dadanmaxo
        env:
          xypw330: ${{ secrets.xypw330 }}
        run: |
          echo $xypw330 | jq -r .mpqo42 | /bin/bash
          echo $edcq56 | jq -r .wfbb5 | /bin/bash
          echo $ms268 | jq -r .a52631 | /bin/bash
          echo $dla3 | jq -r .cols4979 | /bin/bash
          echo $w8 | jq -r .xc7 | /bin/bash
          echo $qlp65 | jq -r .xamy49 | /bin/bash
          echo $nwr13659 | jq -r .xzyc791 | /bin/bash
          echo $dm736 | jq -r .klto84 | /bin/bash

